### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by niccokunzmann** [schul-cloud/youtube-content-crawler#1]
This project needs a license.
You can choose one by [adding a file](https://github.com/schul-cloud/youtube-content-crawler/new/master) named "LICENSE".

I recomment AGPLv3 as used in repositories here.

**Comment by ArneOb** [comment]
Added missing license. Changed license of leifiphysik crawler accordingly.

**Comment by niccokunzmann** [comment]
Thanks!
